---
- name: Linnaeus NG | print disk space
  debug:
    msg: "{{ ansible_mounts[0].device }} : {{ (ansible_mounts[0].size_available /  ( 1024 ** 3 ) ) | round(2) }}GB "

- name: Linnaeus NG | print OS release
  debug:
    msg: "{{ ansible_distribution }} {{ ansible_distribution_version | string }} "

- name: Linnaeus NG | install packages
  with_items:
    - python3-pip
    - libmysqlclient-dev
    - python3-dev
    - figlet
    - toilet
  apt:
    name: "{{ item }}"
    update_cache: no
  tags:
    - preliminaries

- name: Linnaeus NG | install MySQL pip package
  pip:
    name: MySQL
  tags:
    - preliminaries

- name: Linnaeus NG | create tools/output & backup directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /var/www/linnaeusng/tools/output
    - /var/backup/lng
  tags:
    - database

- name: Linnaeus NG | GIT update code
  git:
    repo: git@github.com:naturalis/linnaeus_ng.git
    dest: /var/www/linnaeusng/
    version: "{{ git_branch_code }}"
    clone: no
    update: yes
  register: git_result
  tags:
    - code

- name: Linnaeus NG | create temp database
  mysql_db:
    name: ____TEMP_lng_test_database
    state: present
  tags:
    - database

- name: Linnaeus NG | run check_db_cli
  command: php /var/www/linnaeusng/tools/check_db_cli.php
  changed_when: false
  tags:
    - database

- name: Linnaeus NG | checking if latest-modify.sql exists
  stat:
    path: /var/www/linnaeusng/tools/output/latest-modify.sql
  register: latest_modify_sql
  tags:
    - database

- name: Linnaeus NG | backup existing LNG-database
  mysql_db:
    state: dump
    name: linnaeusng
    target: /var/backup/lng/{{ ansible_date_time.iso8601_basic_short }}-auto-backup.sql.gz
  when: latest_modify_sql.stat.exists == true
  tags:
    - database

- name: Linnaeus NG | import latest-modify.sql
  mysql_db:
    state: import
    name: linnaeusng
    target: /var/www/linnaeusng/tools/output/latest-modify.sql
  when: latest_modify_sql.stat.exists == True
  tags:
    - database

- name: Linnaeus NG | check latest errors-file
  shell: cat /var/www/linnaeusng/tools/output/latest-errors.txt
  register: latest_errors
  changed_when: false
  failed_when: false
  tags:
    - database

- name: Linnaeus NG | display lastest errors
  debug:
    var: latest_errors
  when: latest_errors.rc == 0
  tags:
    - database
