#
# Ansible script used for dumping the old databases and configuration 
# files of the former production machines (june 2018, Linnaeus 2.5.x)
#
- hosts: source
  tasks:

      - name: install packages
        with_items:
         - python3-pip
         - libmysqlclient-dev
         - python3-dev
         - python-mysqldb
        apt:
           name: "{{ item }}"

      - name: Linnaeus NG | checking if config directory exists
        stat:
            path: '/root/lng_config'
        register: config_dir
        tags: fetch

      - name: Linnaeus NG | create linnaeus directory 
        shell: 'mkdir /root/lng_config'
        when: config_dir.stat.exists == false
        tags: fetch

      - name: dump database
        mysql_db:
            state: dump
            name: linnaeusng
            target: /root/lng_config/linnaeus_ng.sql

      - name: crontab dump
        shell: crontab -l > /root/lng_config/crontab.txt
        tags: fetch

      - name: copy htaccess
        shell: '[ -e /var/www/linnaeusng/.htaccess ] && cp /var/www/linnaeusng/.htaccess /root/lng_config/htaccess'
        tags: fetch
        ignore_errors: yes

      - name: copy media
        shell: cp -r /var/www/linnaeusng/www/shared/media /root/lng_config/media-shared
        tags: fetch
        ignore_errors: yes

      - name: copy app media
        shell: cp -r /var/www/linnaeusng/www/app/media /root/lng_config/media-app
        tags: fetch
        ignore_errors: yes

      - name: copy rewrites
        shell: cp -r /var/www/linnaeusng/configuration/app/rewrite /root/lng_config/rewrite-configuration-app
        tags: fetch
        ignore_errors: yes

      - name: copy app configuration
        shell: cp /var/www/linnaeusng/configuration/app/configuration.php /root/lng_config/configuration-app.php
        tags: fetch

      - name: copy app constants
        shell: cp /var/www/linnaeusng/configuration/app/constants.php /root/lng_config/constants-app.php
        tags: fetch

      - name: copy admin configuration
        shell: cp /var/www/linnaeusng/configuration/admin/configuration.php /root/lng_config/configuration-admin.php
        tags: fetch

      - name: copy admin constants
        shell: cp /var/www/linnaeusng/configuration/admin/constants.php /root/lng_config/constants-admin.php
        tags: fetch

      - name: tar project
        shell: (cd /root && tar czf /root/lng-{{ ansible_hostname }}-{{ ansible_date_time.iso8601_basic_short }}.tgz ./lng_config && rm -rf ./lng_config)
        tags: fetch

      - shell: (cd /root; find . -name '*.tgz' -type f) | cut -d '/' -f2
        register: files_to_copy
        tags: fetch

      - name: fetch linnaeus config
        fetch: src=/root/{{ item }} dest=../lng/
        with_items: "{{ files_to_copy.stdout_lines }}"
        tags: fetch

