- hosts: test-notused
  tasks:
      #    - name: Linnaeus NG | replace master git
      #shell: '(cd /opt/docker-linnaeusng && /usr/local/bin/docker-compose exec -T linnaeus bash -c "cd .. && git clone git@github.com:naturalis/linnaeus_ng.git && rm -rf html/.git && mv linnaeus_ng/.git html/ && rm -rf linnaeus_ng && cd html/ && git checkout -- . ")'
    - name: Linnaeus NG | replace development git
      shell: '(cd /opt/docker-linnaeusng && /usr/local/bin/docker-compose exec -T linnaeus bash -c "cd .. && git clone git@github.com:naturalis/linnaeus_ng.git && cd linnaeus_ng && git fetch origin development:development && git checkout development && cd .. && rm -rf html/.git && mv linnaeus_ng/.git html/ && rm -rf linnaeus_ng && cd html/ && git checkout -- . ")'
